sonar.projectKey=project-fosu-smart-border
sonar.projectName=Project Fosu Smart Border Ingress Alert System
sonar.sourceEncoding=UTF-8
sonar.sources=1-app-source-code,2-infrastructure-as-code
sonar.exclusions=**/__pycache__/**,**/.terraform/**,**/*.tfstate*,**/tfplan*,**/*.pfx,**/*.der,**/*.b64
