variable "subscription_id" {
  type        = string
  description = "Azure subscription ID."
}

variable "location" {
  type        = string
  description = "Azure region with availability zone support."
  default     = "eastus2"
}

variable "name_prefix" {
  type        = string
  description = "Lowercase, short resource name prefix."
  default     = "fosu"
}

variable "environment" {
  type    = string
  default = "prod"
}

variable "kubernetes_version" {
  type        = string
  default     = null
  description = "AKS control-plane version. Null lets Azure use the current default supported version. Pin only after checking `az aks get-versions`."
}

variable "aks_admin_group_object_ids" {
  type        = list(string)
  default     = []
  description = "Entra ID group object IDs granted cluster-admin via AKS-managed AAD RBAC. Empty means only principals with an explicit 'Azure Kubernetes Service RBAC Cluster Admin' assignment (e.g. the deployer) can administer the cluster."
}

variable "waf_max_request_body_size_in_kb" {
  type        = number
  default     = 2000
  description = "Application Gateway WAF_v2 max request body size (KB). Range 8-2000; the 128 KB default is often too small for dashboard POSTs."
}

variable "waf_file_upload_limit_in_mb" {
  type        = number
  default     = 100
  description = "Application Gateway WAF_v2 file upload limit (MB)."
}

variable "dashboard_hostname" {
  type        = string
  description = "Public DNS hostname for the dashboard."
}

variable "deployer_ip_cidr" {
  type        = string
  default     = ""
  description = "Public IP (or CIDR) of the machine running Terraform, allow-listed on the Key Vault firewall so secrets can be written. Remove/tighten after initial deploy."
}

variable "dashboard_tls_certificate_base64" {
  type        = string
  sensitive   = true
  description = "Base64-encoded PFX certificate for the public dashboard hostname."
}

variable "dashboard_tls_certificate_password" {
  type        = string
  sensitive   = true
  description = "Password for the dashboard PFX certificate."
}

variable "postgres_admin_username" {
  type      = string
  default   = "fosuadmin"
  sensitive = true
}

variable "postgres_admin_password" {
  type        = string
  sensitive   = true
  description = "Use TF_VAR_postgres_admin_password or a CI secret."
}

variable "postgres_sku_name" {
  type        = string
  default     = "GP_Standard_D2ds_v5"
  description = "PostgreSQL Flexible Server SKU. Use a B-series (e.g. B_Standard_B1ms) for cheap non-production environments."
}

variable "postgres_storage_mb" {
  type        = number
  default     = 32768
  description = "PostgreSQL Flexible Server storage in MB."
}

variable "postgres_high_availability_enabled" {
  type        = bool
  default     = true
  description = "Enable zone-redundant HA (roughly doubles compute cost). Disable for non-production."
}

variable "postgres_geo_redundant_backup_enabled" {
  type        = bool
  default     = true
  description = "Enable geo-redundant backups. Disable for non-production."
}

variable "postgres_backup_retention_days" {
  type        = number
  default     = 14
  description = "PostgreSQL backup retention in days (7-35)."
}

variable "dashboard_username" {
  type    = string
  default = "fosu.admin"
}

variable "dashboard_password_hash" {
  type        = string
  sensitive   = true
  description = "Scrypt hash generated by set_dashboard_password.py."
}

variable "vpn_client_address_pool" {
  type    = list(string)
  default = ["172.30.0.0/24"]
}

variable "vpn_root_certificate_data" {
  type        = string
  sensitive   = true
  description = "Base64-encoded public root certificate for point-to-site VPN."
}

variable "monitoring_namespace" {
  type        = string
  default     = "monitoring"
  description = "Kubernetes namespace for the Loki/Prometheus/Grafana stack. Must match the namespace the monitoring playbook installs into (the Loki federated identity subject is bound to it)."
}

variable "loki_storage_replication_type" {
  type        = string
  default     = "LRS"
  description = "Replication for the Loki log-chunk storage account (LRS, ZRS, GRS)."
}
