variable "subscription_id" {
  type        = string
  description = "Azure subscription ID."
}

variable "location" {
  type        = string
  description = "Azure region with availability zone support."
  default     = "eastus2"
}

variable "name_prefix" {
  type        = string
  description = "Lowercase, short resource name prefix."
  default     = "fosu"
}

variable "environment" {
  type        = string
  default     = "prod"
}

variable "dashboard_hostname" {
  type        = string
  description = "Public DNS hostname for the dashboard."
}

variable "deployer_ip_cidr" {
  type        = string
  default     = ""
  description = "Public IP (or CIDR) of the machine running Terraform, allow-listed on the Key Vault firewall so secrets can be written. Remove/tighten after initial deploy."
}

variable "dashboard_tls_certificate_base64" {
  type        = string
  sensitive   = true
  description = "Base64-encoded PFX certificate for the public dashboard hostname."
}

variable "dashboard_tls_certificate_password" {
  type        = string
  sensitive   = true
  description = "Password for the dashboard PFX certificate."
}

variable "postgres_admin_username" {
  type      = string
  default   = "fosuadmin"
  sensitive = true
}

variable "postgres_admin_password" {
  type        = string
  sensitive   = true
  description = "Use TF_VAR_postgres_admin_password or a CI secret."
}

variable "dashboard_username" {
  type    = string
  default = "fosu.admin"
}

variable "dashboard_password_hash" {
  type        = string
  sensitive   = true
  description = "Scrypt hash generated by set_dashboard_password.py."
}

variable "vpn_client_address_pool" {
  type        = list(string)
  default     = ["172.30.0.0/24"]
}

variable "vpn_root_certificate_data" {
  type        = string
  sensitive   = true
  description = "Base64-encoded public root certificate for point-to-site VPN."
}
