---
terraform_dir: "{{ playbook_dir }}/../Terraform"
image_tag: "latest"
image_repository: "ceteris90/project-fosu"

fosu_namespace: "project-fosu"
dashboard_hostname: "dashboard.example.gov.gh"

# Keep this file encrypted with ansible-vault after populating it.
database_url: "postgresql+psycopg2://USER:PASSWORD@PRIVATE_POSTGRES_FQDN:5432/fosu?sslmode=require"
dashboard_username: "fosu.admin"
dashboard_password_hash: "scrypt$..."

kubernetes_manifest_dir: "{{ playbook_dir }}/../kubernetes"
